### ISSUE TITLE
Can't use your nuget package in my iOS App

### ISSUE THREAD

**Issue by andreaskviby** [softlion/XamSvg-Samples#10]
I have created a standard iOS Xamarin Forms app and wanted to add your svg library to handle svg files in our app. When I added your nuget package I get this error.

Package 'Softlion.XamSvg.Free 2.4.7' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by softlion** [comment]
You are using an old package with is not listed anymore.

Use https://www.nuget.org/packages/Vapolia.Xamarin.Svg.Forms instead.
