### ISSUE TITLE
Can't test without having to buy

### ISSUE THREAD

**Issue by quakeulf** [softlion/XamSvg-Samples#2]
Hi, I would like to test or at least get a demonstration of an animated SVG running in iOS and 'Roid to prove that this package is capable of it.

Unfortunately, I cannot run these examples without having bought the packages (for Xamarin Forms in my case), but before I pay I want to make sure this works. Please help me out.

**Comment by softlion** [comment]
Hi there !
There is a streamed appetize.io IOS demo on www.vapolia.fr

The currently uploaded demo does not display animated SVG but it can be added.

**Comment by softlion** [comment]
You can now try for free directly by using the nuget.
