### ISSUE TITLE
[Forms][iOS] SVG file not selected when it should be

### ISSUE THREAD

**Issue by toussam** [softlion/XamSvg-Samples#7]
Hi Benjamin, :)

### Description

As you know, we are using your component and we noticed an issue that may be related to it.

To summarize our situation, we created a custom control on which we binded some data thanks to the BindableProperties. Inside this control, we set an SVG that is selectable and when it's the case, a part of the file must fill itself.

Everything is working fine except when we are using the custom control into a ListView's DataTemplate. Indeed, some items are not correctly display (must be filled, but aren't). 

### Steps to Reproduce

I created a sample to reproduce the related issue. Into this last one, you will find a simple ListView displaying a .SVG file (a star) by using a custom control. I tried to display the svg with another component and it worked fine.

1. lunch the given sample on an iOS device
2. scroll a bit down and / or up
3. observe that some stars are not filled when they should be

### Basic Information

- Version with issue:
 - Vapolia.XamSvg.Forms --> 3.0.0
 - Xamarin.Forms --> 3.3.0.912540

- Last known good version: Unknow
- IDE: Visual Studio Community 2017, v15.8.4

### Reproduction Link

[Sample.zip](https://github.com/softlion/XamSvg-Samples/files/2525267/Sample.zip)

I thank you in advance for everything and wish you a great week !

**Comment by toussam** [comment]
Hi @softlion ,

Would you have some time to review our issue ? :)

**Comment by toussam** [comment]
Hi @softlion ,

Any update ? ;)

Best regards,

**Comment by softlion** [comment]
try yo set isasync to false. sometimes xamarin forms has issues refreshing a ui zone.

**Comment by toussam** [comment]
I am not sure what you are referring to... Are you talking about the SvgImage's IsLoadAsync ?

The only thing I could find about an IsAsync property is a WPF one using through the binding system.

**Comment by softlion** [comment]
Yes IsLoadAsync  sorry

**Comment by toussam** [comment]
Setting it to False or True is not changing anything.

Another idea maybe ?

**Comment by toussam** [comment]
Hi Benjamin,

I know that you must be very busy, but could you help me with this issue ?

I thank you in advance for everything !

**Comment by softlion** [comment]
Command won't work inside a listview item, because of the way gestures are handled in xamarin forms. This is not a XamSvg issue.
Use DebugListView.ItemTapped instead.
