### ISSUE TITLE
Native Android set SVG in XML

### ISSUE THREAD

**Issue by Dooks123** [softlion/XamSvg-Samples#8]
I'm trying to set an SVG image located in the `Resources/raw/..` folder in the layout xml

```
<XamSvg.SvgImageView
    android:id="@+id/imgIcon"
    android:layout_width="25dp"
    android:layout_height="wrap_content"
    app:svg="@raw/myimg" />
```
to no avail. How do I set an image in XML in native android?

I have tried
- app:svg="res:raw.myimg"
- app:svg="res:myimg"
- app:svg="res:@raw/myimg"

**Comment by softlion** [comment]
don't use res: :), res: is for .NET embedded resources, not android resources.
